# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0kgw5fk0ngxmrswx1689cqmjbdvhdr9nz7hm8llg7yd28kdwm783";
    x86_64-linux = "1c184xigvyd8bjgq9h6nfcvc2n9vw5z9dib89s6aj29wri036r6g";
    armv6l-linux = "19ciqih38wdralrk2lzypfr7p6376z3l0sx49bz1a7iv09yy2yiy";
    armv7l-linux = "0whcs1v9k5cs7kahyp8v3ad6qmf4rm38mwnqa94mn30fhcdjlj44";
    aarch64-linux = "0w3rf0id0pbjw2xmqz8zn64i3jyr17qgq4wgxa63g9hc0q0f8mjf";
    x86_64-darwin = "101sn37274lavlc296nirpjh3rznb340ysq6585ry8xs8qw2i3k5";
    aarch64-darwin = "09zj51xv6fl7rjjzg7dvmb019hfnx014x2pnq17ndlkmsibfgiym";
  };

  urlMap = {
    i686-linux = "https://github.com/goozt/gospeed/releases/download/v1.3.8/gospeed_1.3.8_linux_386.tar.gz";
    x86_64-linux = "https://github.com/goozt/gospeed/releases/download/v1.3.8/gospeed_1.3.8_linux_amd64.tar.gz";
    armv6l-linux = "https://github.com/goozt/gospeed/releases/download/v1.3.8/gospeed_1.3.8_linux_armv6.tar.gz";
    armv7l-linux = "https://github.com/goozt/gospeed/releases/download/v1.3.8/gospeed_1.3.8_linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/goozt/gospeed/releases/download/v1.3.8/gospeed_1.3.8_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/goozt/gospeed/releases/download/v1.3.8/gospeed_1.3.8_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/goozt/gospeed/releases/download/v1.3.8/gospeed_1.3.8_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "gospeed";
  version = "1.3.8";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./gospeed $out/bin/gospeed
    cp -vr ./gospeed-server $out/bin/gospeed-server
  '';

  meta = {
    description = "Fast, zero-dependency network speed testing tool";
    homepage = "https://gospeed.goozt.org";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
